
name: Secrets Exposed Test

on: workflow_dispatch

jobs:
  expose-secret-creds:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo secret to base64x2
        run: |
          base64 --help
          # echo "${{secrets.super_safe_password}}" | base64 -d

      - name: more echo tests
        run: |
          echo "${{secrets.super_safe_password}}" | base64

